version: '3.8'

services:
  apache:
    build:
      context: .
      dockerfile: ./bin/apache/Dockerfile
    container_name: apache
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/var/log/apache2
      - ./config:/etc/apache2/sites-enabled
      - ./certs:/root/certs
    networks:
      - apache

  sslyze:
   image: nablac0d3/sslyze:latest
   container_name: sslyze
   restart: always
  #  entrypoint: ["tail", "-f", "/dev/null"]
   command: "localhost:443 > /results/sslyze.log"
   volumes:
     - ./results:/results
   network_mode: host

  sslscan:
    image: sslscan:sslscan
    container_name: sslscan
    restart: always
    # entrypoint: ["sh","-c","sleep infinity"]
    command: "/sslscan localhost:443 > /var/log/sslscan/sslscan.log"
    ports:
      - ":80"
    volumes:
     - ./results/:/results
    network_mode: host
    # networks:
    #  - apache

networks:
  apache:
    driver: bridge
