version: '3.8'

services:
  apache:
    build:
      context: .
      dockerfile: ./bin/apache/Dockerfile
    container_name: apache
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/var/log/apache2
      - ./config:/etc/apache2/sites-enabled
      - ./certs:/root/certs
    networks:
      - apache

  sslyze:
   image: nablac0d3/sslyze:latest
   container_name: sslyze
  #  entrypoint: ["tail", "-f", "/dev/null"]
   command: "localhost:443 --cert /certs/client.cer --key /certs/client.key > ./results/sslyze.log"
   volumes:
     - ./results:/results
     - ./certs/client:/certs
   network_mode: host

  sslscan:
    image: sslscan:sslscan
    container_name: sslscan
    # entrypoint: ["sh","-c","sleep infinity"]
    command: "/sslscan --pk=/certs/client.p12 --pkpass=myCert localhost:443 > ./results/sslscan.log"
    volumes:
     - ./results/:/results
     - ./certs/client:/certs
    network_mode: host

networks:
  apache:
    driver: bridge
